default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "password" %>
  host: localhost     
  port: 5433           

development:
  <<: *default
  database: sistema_biblioteca_development

test:
  <<: *default
  database: sistema_biblioteca_test

production:
  primary:
    <<: *default
    database: sistema_biblioteca_production
  cache:
    <<: *default
    database: sistema_biblioteca_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: sistema_biblioteca_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: sistema_biblioteca_production_cable
    migrations_paths: db/cable_migrate
