version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sistema_biblioteca_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 80
    volumes:
      - .:/rails
    ports:
      - "3000:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
    depends_on:
      - db

volumes:
  postgres_data:
